name: CI

on:
  push:
    branches:
      - disfactory

  pull_request:
    branches:
      - disfactory
   

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # setup the repository in the runner
      - name: Setup Node.js # setup Node.js in the runner
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile # install dependencies
      - run: yarn build # build the project

      # deploy to github page
      - uses: JamesIves/github-pages-deploy-action@3.7.1
      - name: Deploy to GitHub Pages
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: disfactory
        BRANCH: gh-pages
        SINGLE_COMMIT: true
        COMMIT_MESSAGE: Deploy [ci skip]
        FOLDER: dist